config/routes.rb
Rails.application.routes.draw do
	resource :welcome

	resources :dramas do	
		resources :seasons
		resources :participations
	end
	
	resources :episodes
	
	resources :actors
	
	resources :participations

	root 'dramas#index'
	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/episode.rb
class Episode < ApplicationRecord
  belongs_to :season

  validates :episode_num, presence: true
  
  def <=>(other)
    self.episode_num <=> other.episode_num
  end
end 

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :drama
  belongs_to :actor

  validates :actor, uniqueness: { scope: :drama, message: 'Duplicate actor in a drama' }
end

app/models/season.rb
class Season < ApplicationRecord
	belongs_to :drama
	has_many :episodes, dependent: :destroy

	validates :season_num, :num_total_episode, presence: true
	
	def <=>(other)
		self.season_num <=> other.season_num
 	end
end

app/models/user_ip.rb
class UserIp < ApplicationRecord
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
    def index
        @actors = Actor.all 
    end

    def new
        @actor = Actor.new
    end

    def edit
        @actor = Actor.find(params[:id])      
    end

    def show
        @actor = Actor.find(params[:id])
    end

    def create   
        #render plain: params[:actor].inspect

        @actor = Actor.new(actor_params)
        if @actor.save
			redirect_to actors_path
		else
			render 'new'
		end
    end

    def update
        @actor = Actor.find(params[:id])

        if @actor.update(actor_params)
			redirect_to actors_path
		else
			render 'edit'
		end  
    end

    def destroy
        @actor = Actor.find(params[:id])
		@actor.destroy
		
		redirect_to actors_path      
    end

    private
        def actor_params
            params.require(:actor).permit(:name, :eng_name, :img_url, :birthdate, :birthplace, :height, :weight, :blood, :spouse, :company)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	http_basic_authenticate_with name: "minami", password: "minami"


end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController


	def show
		@episode = Episode.find(params[:id])
	end


end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController
    def index
        @participations = Participation.all
    end

    def new
        @drama = Drama.find(params[:drama_id])
        @participation = Participation.new
    end

    def create
         #render plain: params[:participation].inspect

		@participation = Participation.new(participation_params)
		
		if @participation.save
			redirect_to drama_path(@participation.drama)
		else
			render 'new'
        end

    end   

    def destroy        
        @participation = Participation.find(params[:id])
        drama_id = @participation.drama_id
		@participation.destroy
		
		redirect_to drama_path(drama_id)
    end
    
    private
        def participation_params
            params.require(:participation).permit(
                :drama_id, :actor_id)
        end
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
	def new
		@drama = Drama.find(params[:drama_id])
		@season = @drama.seasons.build
	end
	
	def edit
		@season = Season.find(params[:id])
	end
	
	def create
		#render plain: params[:season].inspect	 

		@drama = Drama.find(params[:drama_id])
		@season = @drama.seasons.build(season_params)
		
		1.upto(season_params[:num_total_episode].to_i) do |num|
			episode_params = { episode_num: num }
			episode = @season.episodes.build(episode_params)
		end

		if @season.save
			redirect_to @drama
		else
			render 'new'
		end

	end
	
	def update
		@season = Season.find(params[:id])
		
		if @season.update(season_params)
			redirect_to @season.drama
		else	
			render 'edit'
		end
	end
	
	def destroy
		@season = Season.find(params[:id])		
		belonged_drama = @season.drama
		@season.destroy
		
		redirect_to belonged_drama
	end
	
	private
		def season_params
			params.require(:season).permit(
				:season_num, :director, :actor,
				:start_date, :synopsis, :file_extension, :num_total_episode)
		end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def is_admin
        request.host == 'dev-drama.minami.im'
    end

    def signed_url_for(url)
        signer = Aws::CloudFront::UrlSigner.new(
          key_pair_id: "APKAILLI34P5LFBKPJ6A",
          private_key_path: (Rails.root + "app/assets/aws/cloudfront.pem")
        )
        
        duration = 60 * 60 * 3
        expires = (Time.now.getutc + duration).to_i.to_s
        policy = %Q/{"Statement":[{"Resource":"#{url}","Condition":{"DateLessThan":{"AWS:EpochTime":#{expires}}}}]}/
            
        signed_url = signer.signed_url(url, policy: policy )
    end

    def s3_image_url
        'https://d3qr8sq75zx535.cloudfront.net/image/'
    end
    
    def s3_video_url
        'https://d3qr8sq75zx535.cloudfront.net/video/'
    end

	def image_url (path)
		signed_url_for(s3_image_url + path + '.jpg')
    end
    
    def video_url (path, extension)
		signed_url_for(s3_video_url + path + '.' + extension)
    end
    
    def video_file_path(episode)
        # drama/season/episode_num
        season = Season.find(episode.season_id)
		file_extension = season.file_extension
        drama = Drama.find(season.drama_id)
        path = drama.eng_title + '/' + format('%02d', season.season_num) + '/' + format('%02d', episode.episode_num)
        return video_url(path, file_extension)
    end
end

app/views/actors/_form.html.erb
<%= form_with(model: @actor, local: true) do |form| %>

<div class="row">	
	<% if @actor.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@actor.errors.count, "error") %> 
					prohibited this season from being saved:
			</h2>
			<ul>
				<% @actor.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>	
</div>  
<div class="row">
	<div class="col">
		<table class="table">
			<tr>
				<td><%= form.label '名前' %></td>
				<td><%= form.text_field :name %></td>
			</tr>
			<tr>
				<td><%= form.label 'Name' %></td>
				<td><%= form.text_field :eng_name %></td>
			</tr>
			<tr>
				<td><%= form.label '生年月日' %></td>
				<td><%= form.date_field :birthdate %></td>
			</tr>
			<tr>
				<td><%= form.label '出身地' %></td>
				<td><%= form.text_field :birthplace %></td>
			</tr>
			<tr>
				<td><%= form.label '身長' %></td>
				<td><%= form.number_field :height %></td>
			</tr>
			<tr>
				<td><%= form.label '体重' %></td>
				<td><%= form.number_field :weight %></td>
			</tr>
			<tr>
				<td><%= form.label '血液型' %></td>
				<td><%= form.text_field :blood %></td>
			</tr>
			<tr>
				<td><%= form.label '配偶者' %></td>
				<td><%= form.text_field :spouse %></td>
			</tr>
			<tr>
				<td><%= form.label '所属社' %></td>
				<td><%= form.text_field :company %></td>
			</tr>

		</table>
	</div>
</div>
<div class="row">
	<div class="col">
		<input type="submit" class="btn btn-warning" value="このデータで登録する">
	</div>
</div>
<div class="row" style="margin-top:1em">
	<div class="col">
		<button type="button" class="btn btn-info"  onclick="location.assign('<%= actors_path %>')">戻る</button>
	</div>
</div>
<% end %>

app/views/actors/edit.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>俳優の情報を修正してください</h1>
    <%= render 'form' %>
</div>

app/views/actors/index.html.erb
<!-- actors index -->

<script>
$(document).ready(function() {  
    set_image_aspect_ratio("img-actor", 1.3);
    set_image_aspect_ratio("img-drama", 0.7);
})  

</script>

<div id="main-container" class="container" style="margin-top:2%">
    <div class="row"style="margin-bottom:30px">
    <!--
        <div class="col-8">
            <h1>南くんのドラマチャンネル</h1>
        </div> -->
        <div class="col-12">            
            <button type="button" style="align-self: center;" class="btn btn-info" 
                onclick="location.assign('<%= dramas_path %>')">ドラマから探す</button>
            
        </div>
    </div>
    <div class="row justify-content-start" style="margin-bottom:30px">
        <% @actors.sort_by { |x| x.name } .each do |actor| %>   
            <div class="col-xs-3 col-lg-2">
                <div><a href="<%= actor_path(actor)%>">
                    <img class="img-actor" style="width:100%;" src="<%= image_url(actor.eng_name) %>"></a>
                </div>
                <div style="height: 1.1em; overflow:hidden"><strong><%= actor.name %></strong></div>
                <div>
                <% if is_admin %>
                    <%= link_to '修正', edit_actor_path(actor) %>
                    <%= link_to '削除', actor_path(actor), method: :delete, 
                        data: { confirm: '削除しますか？' } %>
                <% end %>
                </div>
                <div style="height: 1.1em"></div>
            </div>
        <% end %>
    </div>
    <% if is_admin %>
        <div class="row">
            <div class="col">
                <button type="button" class="btn"  onclick="location.assign('<%= new_actor_path %>')">新俳優を登録</button>
            </div>
        </div>
    <% end %>
</div>

app/views/actors/new.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>新しい俳優を登録したください</h1>
    <%= render 'form' %>
</div>

app/views/actors/show.html.erb
<!-- actors show -->

<script> 
$(document).ready(function() {   
	set_image_aspect_ratio("img-actor", 1.3);
    set_image_aspect_ratio("img-drama", 0.7);
})   

</script>
 
<div id="main-container" class="container" style="margin-top:2%">

<div class="row"style="margin-bottom:30px">
	<div class="col-xs-6">            
		<button type="button" style="align-self: center;" class="btn btn-info" 
			onclick="location.assign('<%= dramas_path %>')">ドラマから探す</button>
		
	</div>
	<div class="col-xs-6 text-right">		
		<button type="button" style="align-self: center;" class="btn btn-danger" 
			onclick="location.assign('<%= actors_path %>')">俳優から探す</button>		
	</div>
</div>

<div class="row"style="margin-bottom:30px">
	<div class="col-xs-6 col-lg-3">            
		<img class="img-actor" style="width:100%;"src="<%= image_url(@actor.eng_name) %>">		
	</div>
	<div class="col-xs-6 col-lg-9">		
		<h2><%= @actor.name %></h2>
		<p><strong>生年月日</strong> <%= @actor.birthdate %></p>
		<p><strong>出身地</strong> <%= @actor.birthplace %></p>
		<p><strong>身長</strong> <%= @actor.height %></p>
		<p><strong>体重</strong> <%= @actor.weight %></p>		
		<p><strong>血液方</strong> <%= @actor.blood %></p>
		<p><strong>配偶者</strong> <%= @actor.spouse %></p>
		<p><strong>所属社</strong> <%= @actor.company %></p>
				
    </div>
</div>


<div class="row"style="margin-bottom:30px">
    <% @actor.dramas.each do |drama| %>
        <div class="col-xs-4 col-lg-2">	
            <div><a href="<%= drama_path(drama) %>">
            <img class="img-drama" style="width:100%;"src="<%= image_url(drama.eng_title) %>"></a>
            </div>
            <div style="height: 1.1em; overflow:hidden"><strong><%= drama.title %></strong></div>
        </div>
    <% end %>
</div>


<% if is_admin %>
    <div class="row" style="margin-top:1em">
        <div class="col">
            <%= link_to '修正', edit_actor_path(@actor) %>
            <%= link_to '削除', actor_path(@actor), 
                method: :delete, data: { confirm: '削除しますか？' } %>
        </div>
    </div>
<% end %>

</div>

app/views/dramas/edit.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>ドラマの情報を修正してください</h1>
    <%= render 'form' %>
</div>  

app/views/dramas/index.html.erb
<!-- dramas index -->

<script>
$("#main-container").on('click-row.bs.table', function (e, row, $element) {
	alert('a');
    window.location = $element.data('href');
});

$(document).ready(function() {  
	//set_image_aspect_ratio("drama-thumbnail", 0.7);
	//$("body").fadeIn();
})  
</script>

<style>
	.button {
		text-align
	}
</style>


<div id="main-container" class="container" style="margin-top:2%">

<div class="row justify-content-end" style="margin-bottom:30px">
	<!--
	<div class="col-8">
		<h1>南くんのドラマチャンネル</h1>
	</div>
	-->
	<div class="col-xs-12 text-right">		
		<button type="button" style="align-self: center;" class="btn btn-danger" 
			onclick="location.assign('<%= actors_path %>')">俳優から探す</button>		
	</div>
</div>

<% @dramas.sort_by { |x| x.title } .each do |drama| %>
<div class="row drama-index-row" >		
	<div class="col-xs-4 col-lg-2">
		<img style=" width:100%;cursor: pointer;" class="drama-title drama-thumbnail" 
				src="<%= image_url(drama.eng_title) %>" onclick="location.assign('<%= drama_path(drama) %>')">
	</div>
	<div class="col-xs-8 col-lg-3">
		<h4><strong><%= drama.title %></strong><small></small></h4>	
		<%= drama.start_date.to_s[0..3] %>, <%= drama.genre %><br>
		 <strong><%= drama.num_total_season %></strong>se. (<strong><%= drama.num_total_episode %></strong>ep.)<br>
	</div>
	
	<div class="clearfix visible-xs-block"></div>

	<div class="col-xs-4 col-lg-3 border-right" >						
		<p><%= drama.actor %></p>	
	</div>
	<div class="col-xs-8 col-lg-4 border-top">					
		<p><%= drama.synopsis.truncate(70) %></p>
	</div>	
	<% if is_admin %>
		<div class="col-xs-2 col-lg-1">
			<%= link_to '修正', edit_drama_path(drama) %><br>
			<%= link_to '削除', drama_path(drama), method: :delete, 
				data: { confirm: '削除しますか？' } %>
		</div>
	<% end %>
</div>
<% end %>

<% if is_admin %>
	<div class="row" style="margin-top:3em">
		<div class="col-xs-12">
			<button type="button" class="btn"  onclick="location.assign('<%= new_drama_path %>')">新ドラマを登録</button>
			<!-- <h2><%= link_to '新ドラマを登録', new_drama_path %></h2> -->
		</div>
	</div>
<% end %>
</div>

app/views/dramas/new.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>新しいドラマを登録してください</h1>
    <%= render 'form' %>
</div>  

app/views/dramas/show.html.erb
<!-- dramas show -->

<script> 
function show_season(season_num) {
	$(".season-data").removeClass("show")
	$("#season-" + season_num).addClass("show") 
}

$(document).ready(function() {   
	show_season(1);
	set_image_aspect_ratio("img-actor", 1.3);
    set_image_aspect_ratio("img-drama", 0.7);
})   

</script>

<div id="main-container" class="container" style="margin-top:2%">

<div class="row"style="margin-bottom:30px">
	<div class="col-xs-6">            
		<button type="button" style="align-self: center;" class="btn btn-info" 
			onclick="location.assign('<%= dramas_path %>')">ドラマから探す</button>
		
	</div>
	<div class="col-xs-6 text-right">		
		<button type="button" style="align-self: center;" class="btn btn-danger" 
			onclick="location.assign('<%= actors_path %>')">俳優から探す</button>		
	</div>
</div>

<div class="row drama-show-row">
	<div class="col-xs-12 col-lg-6">  
		<img src="<%= image_url(@drama.eng_title) %>" style="width:100%;"> 
	</div>
	<div class="col-xs-12 col-lg-6">  
		<h2><%= @drama.title %></h2>
		<p><%= @drama.start_date.to_s%></p>
		<p><%= @drama.synopsis %></p>
	</div>
</div> 

<div class="row drama-show-row" style="padding-bottom:0px;">
	<% @drama.actors.each do |actor| %>
		<div class="col-xs-3 col-lg-2">	
				<p><a href="<%= actor_path(actor)%>" >
				<img class="img-actor" style="width:100%;"src="<%= image_url(actor.eng_name) %>"></a><br>
						<strong><%= actor.name %></strong>
					<% if is_admin %>
						<%= link_to '削除', participation_path(@drama.find_participation(actor)), 
								method: :delete, data: { confirm: '削除しますか？' } %>
					<% end %>
				</p>
		</div>
	<% end %>
</div>
 
<div class="row drama-show-row">
	<div class="col-xs-4">			
		<table id="season-list" class="table">
			<% @drama.seasons.sort.each do |season| %>
				<tr>
					<td><button type="button" class="btn btn-primary"
							onclick="show_season(<%= season.season_num %>);">
								<%= "Season " + season.season_num.to_s %></button></td>
					<% if is_admin %>
						<td><%= link_to '修正', edit_drama_season_path(@drama, season.id) %>
						<%= link_to '削除', drama_season_path(@drama, season.id), 
							method: :delete, data: { confirm: '削除しますか？' } %></td>
					<% end %>
				</tr>
			<% end %>
		</table>
	</div>		
	
	<div class="col-xs-8 border-top">
		<% @drama.seasons.sort.each do |season| %>		
				<div id="season-<%= season.season_num %>" class="season-data collapse">					
					<h5>Season <strong><%= season.season_num %></strong></h5>					
					<% season.episodes.sort.each do |episode| %>						
						<button type="button" class="btn" style="margin: 5px"
							onclick="location.assign('<%= episode_path(episode) %>')"><%= episode.episode_num %>話</button>
							
						<!-- <td><%= link_to '修正', edit_episode_path(episode) %>
						<%= link_to '削除', episode_path(episode), method: :delete, 
								data: { confirm: '削除しますか？' } %></td> -->					
					<% end %>
			
					<!-- <p><button type="button" class="btn" 
						onclick="location.assign('<%= new_episode_path%>')">エピソード追加</button></p> -->
				</div>			
		<% end %>
	</div>
</div>

<% if is_admin %>

<div class="row" style="margin-top:1em">
	<div class="col-xs-12">
		<button type="button" class="btn" 
				onclick="location.assign('<%= new_drama_season_path(@drama) %>')">シーズン追加</button>
		<button type="button" class="btn" 
				onclick="location.assign('<%= new_drama_participation_path(@drama) %>')">登場俳優追加</button>
	</div>
</div>
<% end %>

<div class="row drama-show-row">	
	<!--
	<%= link_to '修正', edit_drama_path(@drama) %>

	<%= link_to '削除', drama_path(@drama), method: :delete, 
		data: { confirm: '削除しますか？' } %>
	-->
</div>
</div>

app/views/episodes/_form.html.erb
Episode form

<% if action_name == 'new' 
		arg2 = [ @episode.season, @episode.season.episodes.build ]
	else
		arg2 = @episode 
	end
%>
<%= form_with(model: @episode,
				url: [ @episode.season, @episode ], local: true) do |form| %>
<div class="row">	
	<% if @episode.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@episode.errors.count, "error") %> 
					prohibited this episode from being saved:
			</h2>
			<ul>
				<% @episode.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>	
</div>
<div class="row">
	<div class="col">
		<table class="table">
			<tr>
				<td><%= form.label 'エピソードナンバー' %></td>
				<td><%= form.number_field :episode_num %></td>
			</tr>
			<tr>
				<td><%= form.label 'ファイル名' %></td>
				<td><%= form.text_field :filename %></td>
			</tr>
		</table>
	</div>
</div>
<div class="row">
	<div class="col">
		<input type="submit" class="btn btn-warning" value="このデータで登録する">
	</div>
</div>
<div class="row" style="margin-top:1em">
	<div class="col">
		<button type="button" class="btn btn-info"  onclick="location.assign('<%= drama_path(@episode.season.drama) %>')">戻る</button>
	</div>
</div>
<% end %>


	

app/views/episodes/edit.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>エピソードの情報を修正してください</h1>
    <%= render 'form' %>
</div>

app/views/episodes/new.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>新しいエピソードを登録してください</h1>
    <%= render 'form' %>
</div>

app/views/episodes/show.html.erb
<div id="main-container" class="container" style="margin-top:2%">
<div class="row">
	<div class="col">
        <h4><%= @episode.season.drama.title + " Season " + @episode.season.season_num.to_s %></h4>
        <h4><%= "第 " + @episode.episode_num.to_s + "話" %></h4>
	</div>
</div>

<div class="row">
	<div class="col">
        <video id="episode-video" style="width:100%;" src="<%= video_file_path(@episode) %>" controls autoplay></video>
	</div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-122111001-1"></script>
	<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());

		gtag('config', 'UA-122111001-1');
	</script>

    <title>ドラマ Explorer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/participations/index.html.erb
<script>
$(document).ready(function() {  
    set_image_aspect_ratio("img-drama", 0.7);
	set_image_aspect_ratio("img-actor", 1.3);
}) 
</script>

<style>
    .img-drama { width: 100%; }
    .img-actor { width: 100%; }
</style>

<div id="main-container" class="container" style="margin-top:2%">
    <%  drama_actor_map = { } 
        key_map = { }
        @participations.each do |p| 
            if drama_actor_map[p.drama_id].nil? 
                drama_actor_map[p.drama_id] = [] 
            end
            drama_actor_map[p.drama_id].push(p.actor.id) 
            key_map[[p.drama_id, p.actor_id]] = p.id
        end %>

    <% drama_actor_map.each do |drama_id, actor_ids| %>
        <div class="row border-top" style="margin-bottom:20px;">
            <div class="col-3">
                <p><img class="img-drama" src="<%= Drama.find(drama_id).img_url %>"><br>
                    <%=Drama.find(drama_id).title %></p>
                
            </div>     
            <% actor_ids.each do |actor_id| %>
                <div class="col-lg-1">
                    <p><img class="img-actor" src="<%= Actor.find(actor_id).img_url %>"><br>
                        <%= Actor.find(actor_id).name %></p><%= link_to '削除',
                            participation_path(Participation.find(key_map[[drama_id, actor_id]])),
                            method: :delete, data: { confirm: '削除しますか？' } %>
                    
                </div>
            <% end %>   
        </div> 
    <% end %>
    <div class="row" style="margin-top:1em">
        <div class="col">
            <button type="button" class="btn" 
                    onclick="location.assign('<%= new_participation_path %>')">登場俳優追加</button>
        </div>
    </div>

    <div class="row" style="margin-top:1em">
        <div class="col">
            <button type="button" class="btn btn-info"  onclick="location.assign('<%= dramas_path %>')">ドラマリストへ</button>
        </div>
    </div>
</div>

app/views/participations/new.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>登場俳優を登録してください</h1>
    <%= form_with model: @participation, local: true do |form| %>
    <div class="row">	
        <% if @participation.errors.any? %>
            <div id="error_explanation">
                <h2>
                    <%= pluralize(@participation.errors.count, "error") %> 
                        prohibited this drama from being saved:
                </h2>
                <ul>
                    <% @participation.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %> 
                </ul>
            </div>
        <% end %>	
    </div>	
    <div class="row" style="margin-bottom:30px">	
        <div class="col-3">	
            <%= form.label 'Drama ' %><br><%= form.select :drama_id, 
                options_for_select(Drama.all.map{|s|[s.title, s.id]}, @drama.id) %>
        </div>
        <div class="col-3">	
            <%= form.label 'Actor ' %><br><%= form.select :actor_id, options_for_select(Actor.all.sort_by { |x| x.name }.map{|s|[s.name, s.id]}) %>
        </div>
    </div>
    <div class="row">	
        <div class="col">	
            <input type="submit" class="btn btn-warning" value="このデータで登録する">
        </div>
    </div>
    <% end %>
</div>  

app/views/seasons/_form.html.erb
<%= form_with(model: @season, url: [@season.drama, @season], local: true) do |form| %>
<div class="row">	
	<% if @season.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@season.errors.count, "error") %> 
					prohibited this season from being saved:
			</h2>
			<ul>
				<% @season.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>	
</div>  
<div class="row">
	<div class="col">
		<table class="table">
			<tr>
				<td><%= form.label 'シーズンナンバー' %></td>
				<td><%= form.number_field :season_num %></td>
			</tr>
			<tr>
				<td><%= form.label 'file extension' %></td>
				<td><%= form.text_field :file_extension %></td>
			</tr>
			<tr>
				<td><%= form.label 'トータルエピソード数' %></td>
				<td><%= form.number_field :num_total_episode %></td>
			</tr>
		</table>
	</div>
</div>
<div class="row">
	<div class="col">
		<input type="submit" class="btn btn-warning" value="このデータで登録する">
	</div>
</div>
<div class="row" style="margin-top:1em">
	<div class="col">
		<button type="button" class="btn btn-info"  onclick="location.assign('<%= drama_path(@season.drama) %>')">戻る</button>
	</div>
</div>
<% end %>

app/views/seasons/edit.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>シーズンの情報を修正してください</h1>
    <%= render 'form' %>
</div>

app/views/seasons/new.html.erb
<div id="main-container" class="container" style="margin-top:2%">
    <h1>新しいシーズンを登録したください</h1>
    <%= render 'form' %>
</div>

app/views/welcomes/show.html.erb
<h1>Welcome#index</h1>
<p>Hello, RoR!</p>